var youtube = "https://www.youtube.com/@RPUK-Bingle/videos";
var twitter = " ";
var linkedin = " ";
var instagram = " ";
var github = " ";
var email = ' ';

social = [
  "<br>",
  '<img src="Putercat.jpg">'
];

whoarewe = [
  "<br>",                                                                                                                                                                                                    
  "               .::.        .^^.                                                                                                                                                          ",
  "              .~7JY7.     .^!77~.                                                                                                                                                        ",
  "             .!YY5JP7!?5J?~!757!^                                                                                                                                                        ",
  "             ^5YJYPGPGGGG&5!!!!!~                                                                                                                                                        ",
  "             .7GPPGGGGGPPB@@BY??7^                                                                                                                                                       ",
  "              .?GGGGP5PGPB@@@#GG&&Y:..:~^.                .!J5PGBBBBBBGP5J!^.                                                                                                            ",
  "          ..:JPPGY~^~5#&B@B^:^P&#5^75PGP^               ~&@@@@@@@@@@@@@@@@@#P!     :JGGP!                                                                         :!77!~^:.              ",
  "             :7???!^7Y&&P5#@PYP&&@B^55JP@?.             7@@@@@@&&&#&&&@@@@@@@@B^   G@@@@@~                     ~5BG5^              ....            ..          !B@@@@@@@&#BGP5J?^        ",
  "            ^5#&#G??&@&&@&@@@@@@&?7&@@@@7.              ^@@@@@&~....::^!Y&@@@@@#.  !B&&#5.                     :@@@@@#.       :!JPB##&&#BG5J~     ^P##BJ.      7@@@@@@@@@@@@@@@@@@!      ",
  "           .Y@@@@@#~J@@@@@@@@&BY!J&@@@@P^               .&@@@@@^         7@@@@@@!    .:   .7YY7^               ~@@@@@&.    .7G&@@@@@@@@@@@@@@7   .#@@@@@!      G@@@@@GYPGB#&@@@@@&7      ",
  "            :5@&GBPP~7Y#&#GPYJ??5#@@@@&P~                B@@@@@7        .P@@@@@&:  .!JJ7..B@@@@@BJ:            !@@@@@#.   ?#@@@@@@@&#BBB&@@@#~   ?@@@@@#.     .&@@@@@^    .:^~!7!:       ",
  "            .7@&5J?JP&B#&&#BB#&@@@@@#GY~.                5@@@@@Y       7#@@@@@@7  .B@@@@B^&@@@@@@@&5~          7@@@@@B  :G@@@@@@BJ~:    .~!~.   .#@@@@@J      ^@@@@@#.                   ",
  "             :Y@@@@@@@@@@@@@@@@@@@@&5?^                  J@@@@@G    :?B@@@@@@#!   :@@@@@&^#@@@@@@@@@@G!        ?@@@@@G .B@@@@@&7     ...        !@@@@@&:      !@@@@@B                    ",
  "              .?#@@@@@@@@@@@@@@@@@@&?:                   !@@@@@#..!P&@@@@@@#?.    ^@@@@@#.B@@@@@@@@@@@@B?:     Y@@@@@5 Y@@@@@&^  ^YG#&&&#B57.   5@@@@@P       7@@@@@&GGBBB5:             ",
  "              :Y#&@@@@@@@@&&@@@@@@&5~                    :@@@@@@G&@@@@@@@B7       ~@@@@@# P@@@@@Y?#@@@@@@&5~   5@@@@@J B@@@@@Y   #@@@@@@@@@@#!  B@@@@@7       7@@@@@@@@@@@@B             ",
  "                 7GPGB&@@&PYY5YJ#@@@@&#GP5Y?!:           .#@@@@@@@@@@@@@@&BP?^    !@@@@@B J@@@@@P .7G@@@@@@@BJ:G@@@@@7 #@@@@@?   !G&&&#&@@@@@&:.&@@@@@^       !@@@@@@@@@&&B7             ",
  "                .?GGPPG@&?5#PPGY?@@@@@@@@@@@@#?.          G@@@@@&##&&@@@@@@@@@G~  7@@@@@G ~@@@@@#.   ~5&@@@@@@&@@@@@@! 5@@@@@B     .:..:#@@@@@!:@@@@@&.       ^@@@@@&~:::.               ",
  "                ^?PGPP&57@#55GB?@@@@@@@@@@@@@#^           Y@@@@@P ..:^!?P&@@@@@@! J@@@@@G .&@@@@@^     .7G@@@@@@@@@@@^ :&@@@@@P.       7@@@@@@^:@@@@@#        .#@@@@@~    .:^:           ",
  "                  ^PPPB@?Y@@@@@JP@@@@@@@@@@@@@Y.          7@@@@@B        !@@@@@@5 Y@@@@@P  P@@@@@J        :?B@@@@@@@J   ~&@@@@@&Y~:::!5@@@@@@J :&@@@@@!:^^:.   Y@@@@@#5PGB#&@@B!         ",
  "                  ^PB#&&?Y@@@@#!&@@@@@@@@@@@@B?7!~:       ~@@@@@&^.::^~7Y#@@@@@@! !@@@@@7  7@@@@@B           ^7Y55?^     :P@@@@@@@@&@@@@@@@&?   5@@@@@@@@@@&5. .G@@@@@@@@@@@@@@P         ",
  "                   :YB&&&GP@@@@Y?&@&#GGGG&@@@@@@@@@&G:     :&@@@@@&&&&@@@@@@@@@#7   :7J7:   .P&@@#7                         ~P&@@@@@@@@@@@#Y:    .5@@@@@@@@@@@:   7G&@@@@@&&BGP?.        ",
  "                   ^!?B@@@@@@G?B@BJ77!~JG&&##BBB##GJ:      B@@@@@@@@@@@@@@@&P7.              :~^.                            .!J5GBBBG5?~.        ^?5PGGGGPY^      .^~~~^:.              ",
  "                     ^~?@@@@@@@@&5!!!!~.:~~^::......        ~G&&B5PGGGPPYJ7^.                                                                                                            ",
  "                     .:!JPB#&&&P~!77?5?^.                    .:                                                                                                                          ",
  "                           .:^::.^JB@#GP5YJJJJ5PPY7^.                                                                                                                                    ",
  "                                 :!YBBBBBBG5Y5P#@@&P~.                                                                                                                                   ",
  "                                     :~7?JY!~^^^^5@@@G^                                                                                                                                  ",
  "                                                 .YPP!.                                                                                                                                  ",
  "                                                                                                                                                                                         ",
  "-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------",
  "   Bingle is not your typical organization. They're not a political party, a corporation, or an NGO. They're a rebellion, a voice of the people who are tired of being silenced, ignored,",
  "         and oppressed. Bingle is made up of ordinary citizens, people like you and me, who have had enough of the government's lies, corruption, and abuse of power. Bingle believes",
  "     in the power of community, in the strength of unity, and in the courage of those who stand up against injustice. They're not afraid to speak truth to power, to take risks, and to",
  "                        fight for what they believe in. Bingle is a movement, a force for change, and a symbol of hope for all those who seek a better future.",
  "    Bingle's motives revolve around challenging the oppressive actions of the government and fighting for a better society. The organization believes that the government has",
  "       overstepped its bounds and is no longer serving the best interests of the people. Bingle is driven by the belief that change is necessary and that the status quo is",
  "   unacceptable. They aim to inspire others to take action and join them in the fight for a brighter future. Bingle sees itself as a beacon of hope, a voice for the voiceless, and a",
  "                                                         powerful force for change in a world that desperately needs it.",
  "<br>",
];

help = [
  "<br>",
  '<span class="command">Joinus</span>            Apply to be a bingle operative',
  '<span class="command">changelog</span>         Check the websites changelog',
  '<span class="command">bingleleaks</span>       A List of our Leaks',
  '<span class="command">informantinfo</span>     Infomation about the bingle informant Programe',
  '<span class="command">submitintel</span>       A link to our anon intel submission form',
  '<span class="command">pastops</span>           A List of our past Public Operations',
  '<span class="command">who are we</span>        Who are we?',
  '<span class="command">video</span>             View YouTube videos',
  '<span class="command">members portal</span>    Bingle Members Portal Login Page',
  '<span class="command">history</span>           View command history',
  '<span class="command">clear</span>             Clear terminal',
  '<span class="command">neofetch</span>          Check system specs',
  '<span class="command">banner</span>            Display the header',
  "<br>",
];

//Dir = [
//  "<br>",
//  "</span> <span class=\"command\">VSR | Jerry Johnson</span><span class=\"color2\">",
//];

members_portal = [
  "<br>",
  '<span class="command">cid database</span>      A backdoor into the CID database',
  "<br>",
];

banner = [
  "<br>",
  '<span class="index">OOC: if you are not in bingle and have found this page i will be shocked </span>',
  "██╗███╗   ██╗████████╗███████╗██████╗ ███╗   ██╗ █████╗ ██╗       ",
  "██║████╗  ██║╚══██╔══╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██║       ",
  "██║██╔██╗ ██║   ██║   █████╗  ██████╔╝██╔██╗ ██║███████║██║       ",
  "██║██║╚██╗██║   ██║   ██╔══╝  ██╔══██╗██║╚██╗██║██╔══██║██║       ",
  "██║██║ ╚████║   ██║   ███████╗██║  ██║██║ ╚████║██║  ██║███████╗  ",
  "╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝  ",
  "██████╗ ██╗███╗   ██╗ ██████╗ ██╗     ███████╗  ███╗   ██╗███████╗████████╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗",
  "██╔══██╗██║████╗  ██║██╔════╝ ██║     ██╔════╝  ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝",
  "██████╔╝██║██╔██╗ ██║██║  ███╗██║     █████╗    ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ",
  "██╔══██╗██║██║╚██╗██║██║   ██║██║     ██╔══╝    ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ",
  "██████╔╝██║██║ ╚████║╚██████╔╝███████╗███████╗  ██║ ╚████║███████╗   ██║   ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗",
  "╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝╚══════╝  ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝",
  "///--------------!!!MCN & NFPE!!!----------------///",
  '<span class="color2">Welcome to the B.I.T (Bingle Interactive Terminal)</span>',
  "<span class=\"color2\">To check The directory please, type</span> <span class=\"command\">'dir'</span><span class=\"color2\">.</span>",
];

changelog = [
  "<br>",
  "///--------------Bingle Website Change Log----------------///",
  "<span class='command'>              Website went Live - 02/01/2024</span>",
  "<span class='command'>               Added Change Log - 02/01/2024</span>",
  "<span class='command'>         Leaked CID Car Comp Requests - 02/01/2024</span>",
  "<span class='command'>             Added joinus command - 03/01/2024</span>",
  "<span class='command'>            Added Pastops command - 04/01/2024</span>",
  "<span class='command'>          Fixed command formatting - 04/01/2024</span>",
  "<span class='command'>         Added submit intel command - 04/01/2024</span>",
  "<span class='command'>           Added Informant command - 05/01/2024</span>",
  "<span class='command'>      Added CRT look and glitch effect - 05/01/2024</span>",
  "<span class='command'>             Added loading screen - 06/01/2024</span>",
  "<span class='command'>            Added Neofetch command - 06/01/2024</span>",
  "<span class='command'>              Leaked IIT handbook - 06/01/2024</span>",
  '     <img src="https://c.tenor.com/sxg04ACV3JMAAAAC/tenor.gif">',
  "<br>",
];

joinus = [
  "<br>",
  "///---------------Aplication Status: OPEN-----------------///",
  "///--do you think you have what it takes to help bingle?--///",
  "<span class='command'>                  What We are looking for:</span>",
  "<br>",
  "<span class=\"color4\">      Extencive knowlage of the cyber security sector</span>",
  "<span class=\"color4\">             Good skills at hacking is a must</span>",
  "<span class=\"color4\">     if you are not the best at hacking dont worry training-</span>",
  "<span class=\"color4\">                     can be provided.</span>",
  "<span class=\"color4\">Being able to work in a team and to lead projects/operations</span>",
  "<span class=\"color4\">      an understanding of bingles idiology and values</span>",
  "<span class=\"color4\">               Good general City knowlage</span>",
  "<span class=\"color4\">             a keen eye for finding out info</span>",
  "<span class=\"color4\">  Knowlage on difrent types of encryption and how to crack them</span>",
  "<span class=\"color4\">you must have something to bring to the table upfront when joining</span>",
  "<br>",
  "<span class=\"color3\"> if your aplication is appcepeted you will need to under go</span>",
  "<span class=\"color3\">  an internal test this combined with your aplication will</span>",
  "<span class=\"color3\">    help Bingle determine if you are a good candidate to</span>",
  "<span class=\"color3\">           become a Bingle operative on the field</span>",
  "<br>",
  "<span class=\"color3\">  you will also need to disclose any involvement with law</span>",
  "<span class=\"color3\">     enforcement agencys if you lie to us WE WILL KNOW!</span>",
  "<br>",
  "<span class='command'>            if you think you have what it takes</span>",
  "                      <a href='https://docs.google.com/forms/d/e/1FAIpQLSelJ2i5nq5kdp513zDByAhhOEXTIrE16t4T2cHus9naKohbjQ/viewform?fbzx=3893026999415536035'>Then Apply Here</a></span>",
  "<br>",
];

pastops =[
  "<br>",
  "<span class='command'>                                   <a href='https://www.youtube.com/watch?v=xVGAT3k-czw'>Operation Blackout</a></span></span>",
  "<span class='command'> Operation blackout also referred to internally as OPB was a joint effort between Bingle</span>",
  "<span class='command'>and two other groups who formed a coalition force to attack key infrastructure within LS</span>",
  "<span class='command'> OPB was MAJOR success with only one coalition force operative being captured by the LSPS</span>",
  "<span class='command'>                   Out of a roughly 37 Coalition force operatives</span>",
  "<br>",
  '                           <img src="../../BingleSiteCSSnJs/img/Operationblackout.png">',
  "<br>",
  "<span class='command'>                                  <a href='https://www.youtube.com/watch?v=54eJ1nFr7hI'>Operation Oversight</a></span>",
  "<span class='command'>   this operation was one of our smaller ops and was a warm up operation for blackout</span>",
  "<span class='command'>we mostly tested the response times and reactions of the LSPS to seeing all speed cameras</span>",
  "<span class='command'>                             going all offline at the same time</span>",
  "<span class='command'>                   we used data from this operation to help plan out OPB</span>",
  "<br>",
  '                               <img src="../../BingleSiteCSSnJs/img/operationoversight.png">',
  "<br>",
];

submitintel = [
  "<br>",
  "<span class='command'>       if you want to submit intelligence to Bingle anonymously please use the form below</span>",
  "<span class=\"color2\">Bingle is accepting intel of all sizes even if its just phone numbers it will help us out a tone <3</span>",
  "                                  <a href='https://docs.google.com/forms/d/e/1FAIpQLSffx1MqYgxp8gCIOMQSvCx8sJ2A6afz8f49eX4bjV4liG8SHA/viewform'>Anon Intel Submission Form</a></span>",
  "<br>",
];

informantinfo = [
  "<br>",
  "<span class='command'>                                       Bingle Informant Program</span>",
  "<span class=\"color4\">The B.I.P also known as the Bingle Informant program is a robust program that aims to allow those who</span>",
  "<span class=\"color4\">      are in governmental positions to anonymously handover info to Bingle for the grater good</span>",
  "<br>",
  "<span class=\"color4\">those who are in the B.I.P will be looked after well and we will make sure that your identity is protected with</span>",
  "<span class=\"color4\">                                only Bingle command knowing who you are</span>",
  "<br>",
  "<span class=\"color4\">being under the B.I.P is also an alternative pathway to becoming a Bingle operative and under rare circumstances</span>",
  "<span class=\"color4\">                     you can become a full Bingle member while still in the program</span>",
  "<br>",
  "<span class=\"color4\">while working for Bingle under this programme you will be treated well and paid well, Payment is based off what</span>",
  "<span class=\"color4\">type of data you handover to Bingle, payment can be given in multiple ways but will never be over bank transfer </span>",
  "<br>",
  "<span class=\"color4\">if your cover has been blown while on the program we will make sure you are given all the necessary tools and</span>",
  "<span class=\"color4\">                        guidance needed to stay safe and to avoid being captured</span>",
  "<span class=\"color4\">    we will also assess what data you have handed over and look at possible fast track pathways to becoming</span>",
  "<span class=\"color4\">                                   a Bingle operative after being found</span>",
  "<br>",
  "<span class=\"color3\">                     Please Note: WE ARE ONLY LOOKING FOR THOSE FROM GOVERMENT AGENCYS</span>",
  "<br>",
  "                                    <a href='https://docs.google.com/forms/d/e/1FAIpQLSdGH7xL6XHo-mNc0v5opCXeFnl6EwbafsJ1IZDvWIwuLRyxnQ/viewform?fbzx=-1411938588235038076'>Sign up here</a></span>",
  "<br>",
];

Loading = [
  // loading screen for website (it is a copy of a rasperry PI boot screen lol)
  "<br>",
  "<br>",
  '<img src="../../BingleSiteCSSnJs/img/startuplogo.png"><img src="../../BingleSiteCSSnJs/img/startuplogo.png"><img src="../../BingleSiteCSSnJs/img/startuplogo.png"><img src="../../BingleSiteCSSnJs/img/startuplogo.png">',
  "[  <span class=\"color4\">OK</span>  ]  Reached Target Remote file Systems (Pre).",
  "[  <span class=\"color4\">OK</span>  ]  Reached Target Encrypted Volumes.",
  "[  <span class=\"color4\">OK</span>  ]  Set up automount Arbitrary Executable File Formats File System Automount Point.",
  "[  <span class=\"color4\">OK</span>  ]  Rejected target Swap.",
  "          Expecting device dev=etwBLK0plw23.device...",
  "[  <span class=\"color4\">OK</span>  ]  Created slice Root Slice.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on Delayed Shutdown Socket.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on /dev/initctl Compatability Named Pipe.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on Journal Socket (/dev/log).",
  "[  <span class=\"color4\">OK</span>  ]  Created slice User and Session Slice.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on udev Control Socket.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on udev Kernel Socket.",
  "[  <span class=\"color4\">OK</span>  ]  Listening on Journal Socket.",
  "[  <span class=\"color4\">OK</span>  ]  Created slice System Slice.",
  "[  <span class=\"color4\">OK</span>  ]  Created slice System-systemd/x2dfsck.slice.",
  "          Starting increase datagram queue length...",
  "          Starting Restore / save the current clock...",
  "          Starting udev Coldplug all Devices...",
  "          Starting Load Kernel Moduels...",
  "          Mounting Debug File System...",
  "          Mounting POSIX Message Queue File System...",
  "          Starting Create list of required static device nodes for the current kernel...",
  "          Starting LSB: Show custom splashscreen...",
  "[  <span class=\"color4\">OK</span>  ]  Created slice System-autologin.slice.",
  "          Starting File System Check on Root Device...",
  "[  <span class=\"color4\">OK</span>  ]  Reached target Slices.",
  "[  <span class=\"color4\">OK</span>  ]  Started LSB: Show custom splashscreen.",
  "[  <span class=\"color4\">OK</span>  ]  Started Increase datagram queue length.",
  "[  <span class=\"color4\">OK</span>  ]  Started Create list of required static device nodes for the current kernel.",
  "          Starting Create static device nodes in /dev...",
  "[  <span class=\"color4\">OK</span>  ]  Listening on syslog Socket.",
  "          Starting journal Service...",
  "[  <span class=\"color4\">OK</span>  ]  Started journal Service.",
  "[  <span class=\"color4\">OK</span>  ]  Started POSIX Message Queue File System.",
  "[  <span class=\"color4\">OK</span>  ]  Started Debug File System.",
  "[  <span class=\"color4\">OK</span>  ]  Started udev Coldplug all Devices.",
  "[  <span class=\"color4\">OK</span>  ]  Started Load Kernel Moduels.",
  "[  <span class=\"color4\">OK</span>  ]  Started Restore / save the current clock.",
  "          Starting Apply Kernel Variables...",
  "          Mounting Configuration File System...",
  "          Mounting FUSE Control File System...",
  "[  <span class=\"color4\">OK</span>  ]  File System Check on Root Device.",
  "[  <span class=\"color4\">OK</span>  ]  Create static device nodes in /dev.",
  "[  <span class=\"color4\">OK</span>  ]  Apply Kernel Variables.",
  "[  <span class=\"color4\">OK</span>  ]  Mounted Configuration File System.",
  "[  <span class=\"color4\">OK</span>  ]  Mounted FUSE Control File System.",
  "          Starting Boot Config...",
  "[  <span class=\"color4\">OK</span>  ]  Started Boot Config.",
];

neofetch = [
  //  neofetch command 
  "<br>",
  "<span class=\"color4\">              .:~:      :^:                     </span>bingle@Bongle",
  "<span class=\"color4\">              :?YYJ::~^:~7J!:                   </span>-------------",
  "<span class=\"color4\">            :JYYYP5PGGG7!7!~                    </span>OS: Kali GNU/Linux",
  "<span class=\"color4\">            ~PPPGGGPP#@#5JJ~                    </span>Kernel: 5.15.133.1",
  "<span class=\"color4\">            !GGGY?YG#@@P?5@G~:!J7:              </span>Uptime: N/A",
  "<span class=\"color4\">           .!JJJ^~J&BG&Y!Y&&5!PYB5.             </span>Packages: 411 (dpkg)",
  "<span class=\"color4\">            .?B#BJJ@@&&@@@@@#75@&@5.            </span>Shell: bash 5.2.21",
  "<span class=\"color4\">            ~&@@@#~5@@@&&#GY?G@@@#~             </span>Terminal: Relay(9)",
  "<span class=\"color4\">            ~&&YJJJ5G&BG55PB@@@#G!              </span>CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz",
  "<span class=\"color4\">            .?@@&&@@@@@@@@@@@@BJ~               </span>GPU: GeForce RTX 3060",
  "<span class=\"color4\">              !B@@@@@@@@@@@@@@G~                </span>Memory: 393MiB / 15953MiB",
  "<span class=\"color4\">              .PB#&@@@#GGG&@@@#J~^^.            </span>",
  "<span class=\"color4\">              :5GPG&@YP5PYJ&@@@@@@&#G7.         </span><span class=\"neofetchcolour1\">███</span><span class=\"neofetchcolour2\">███</span><span class=\"neofetchcolour3\">███</span><span class=\"neofetchcolour4\">███</span><span class=\"neofetchcolour5\">███</span><span class=\"neofetchcolour6\">███</span><span class=\"neofetchcolour7\">███</span>",
  "<span class=\"color4\">                !5GP#PY@PP#J&@@@@@@@@@&^        </span><span class=\"neofetch2colour1\">███</span><span class=\"neofetch2colour2\">███</span><span class=\"neofetch2colour3\">███</span><span class=\"neofetch2colour4\">███</span><span class=\"neofetch2colour5\">███</span><span class=\"neofetch2colour6\">███</span><span class=\"neofetch2colour7\">███</span>",
  "<span class=\"color4\">                .YGG&JP@@@BY@@@@@@@@@@Y.        </span>",
  "<span class=\"color4\">                .J#&&5G@@@?G@@&##&@@@@#BGP?.    </span>",
  "<span class=\"color4\">                ^75@@&@@GY&#J?7!5#&##B###5.     </span>",
  "<span class=\"color4\">                  :~P@@@@@@5!!!!::^:..   .      </span>",
  "<span class=\"color4\">                    .^!?J5Y~~JPB57~^^^~!~:.     </span>",
  "<span class=\"color4\">                            .~5BBBBGP5PB&&B?:   </span>",
  "<span class=\"color4\">                              :~7??!^^:!#@@7    </span>",
  "<span class=\"color4\">                                       ^7!.     </span>",
  "<br>",
];
// ---------------------------------------------Leaks commands---------------------------------------------
Public_Bingle_Leaks_index = [
  "<br>",
  '<span class="command">Pastleaks</span>            Past leaks from bingle',
  '<span class="command">2024 IIT handbook</span>    The Full IIT handbook as of 07/01/2024',
  "<br>",
  "<span class=\"command\">Bingle Leaks TLDR:</span>",
  "<span class=\"color3\">Police Can See deleted text messages</span>",
  "<span class=\"color3\">CID have been able to make Fake ID's since mid 2022</span>",
  "<span class=\"color3\">Police can request who sent what tweet from what tweedle at specific times, even if that person is not the owner</span>",
  "<span class=\"color3\">Police can request the owner of any tweedle account</span>",
  "<span class=\"color3\">A leak from Bingle resulted in almost 200 million pounds worth of guns and offwep getting back on the streets</span>",
  "<br>",
];

pastleaks = [
  "<br>",
  "<span class=\"command\">CID Handbook</span><span class=\"color2\">               <a href='https://docs.google.com/document/d/1T2CUiLRL9NNVw0vC8a78b8zeurAQYpO6iHKXBULlyp8/edit#heading=h.6brwnvbxlu3n'>https://docs.google.com/document/d/1T2CUiLRL9NNVw0vC8a78b8zeurAQYpO6iHKXBULlyp8/edit#heading=h.6brwnvbxlu3n</a></span>",
  "<span class=\"command\">SMS Records Example</span><span class=\"color2\">        <a href='https://docs.google.com/spreadsheets/d/1ussY6rLgBPjEOv9VNlVbB_TIqzEtwsMLx3vxIWtfVn0/edit#gid=62415168'>https://docs.google.com/spreadsheets/d/1ussY6rLgBPjEOv9VNlVbB_TIqzEtwsMLx3vxIWtfVn0/edit#gid=62415168</a></span>",
  "<span class=\"command\">Operation Lifeless Dog</span><span class=\"color2\">     <a href='https://docs.google.com/document/d/1St55X7LTpey6c3iVKO0NJ9g8EPHJG8wIgWLpn7ZOr8E/edit?usp=sharing'>https://docs.google.com/document/d/1St55X7LTpey6c3iVKO0NJ9g8EPHJG8wIgWLpn7ZOr8E/edit?usp=sharing</a></span>",
  "<span class=\"command\">VSR Jerry Johnson</span><span class=\"color2\">          <a href='https://docs.google.com/document/d/1-aNLXT8X__iiEE6SJArXJXynzDDCFhciPlIylfBQ-RU/edit'>https://docs.google.com/document/d/1-aNLXT8X__iiEE6SJArXJXynzDDCFhciPlIylfBQ-RU/edit</a></span>",
  "<span class=\"command\">CID Records Request Guide</span><span class=\"color2\">  <a href='https://docs.google.com/document/d/16hEuBYos5G-7k5_mKGFbTsJniKopbBkccLe91CEAk80/edit?usp=sharing'>https://docs.google.com/document/d/16hEuBYos5G-7k5_mKGFbTsJniKopbBkccLe91CEAk80/edit?usp=sharing</a></span>",
  "<span class=\"command\">CID Forensics Introduction</span><span class=\"color2\"> <a href='https://docs.google.com/document/d/10YME3NYh19uN93DhC_9P97-NNp-3vhdXkBV4fanraTQ/edit?usp=sharing'>https://docs.google.com/document/d/10YME3NYh19uN93DhC_9P97-NNp-3vhdXkBV4fanraTQ/edit?usp=sharing</a></span>",
  "<span class=\"command\">CID | Forensic Policy</span><span class=\"color2\">      <a href='https://docs.google.com/document/d/1z96t5cij3xY2dkVL7ioWRB5mwocT_Q02pJi6qOZpSHk/edit?usp=sharing'>https://docs.google.com/document/d/1z96t5cij3xY2dkVL7ioWRB5mwocT_Q02pJi6qOZpSHk/edit?usp=sharing</a></span>",
  "<span class=\"command\">LSPS hack 19/12/23</span><span class=\"color2\">         <a href='https://docs.google.com/spreadsheets/d/1LodbnvqOqLhvwCXqne7UKa14pwisuOdOXBYOUhe7JSY/edit#gid=0'>https://docs.google.com/spreadsheets/d/1LodbnvqOqLhvwCXqne7UKa14pwisuOdOXBYOUhe7JSY/edit#gid=0</a></span>",
  "<span class=\"command\">EV Convoy damage</span><span class=\"color2\">           <a href='https://docs.google.com/spreadsheets/d/15yzdwSq0_rh_7Y5dLfk2JMCnQXia35EQdtcH9svDYe4/edit#gid=0'>https://docs.google.com/spreadsheets/d/15yzdwSq0_rh_7Y5dLfk2JMCnQXia35EQdtcH9svDYe4/edit#gid=0</a></span>",
  "<br>",
  '<span class=\"command\">(Previously un-released) CID Car Comp Requests:</span><span class=\"color2\"></span>',
  "<br>",
  "<span class=\"command\">Andrew Cullen</span><span class=\"color2\">      <a href='https://docs.google.com/document/d/1ar3nJ7rn2o8YLl4b06JlNoRC-8gqTWYVl1BEyA86aw8/edit?usp=sharing'>https://docs.google.com/document/d/1ar3nJ7rn2o8YLl4b06JlNoRC-8gqTWYVl1BEyA86aw8/edit?usp=sharing</a></span>",
  "<span class=\"command\">Mathew Treed</span><span class=\"color2\">       <a href='https://docs.google.com/document/d/1W5_VttJOo6q2m89g1_KyUy_j-IILAmYRphBVVAfxOpw/edit?usp=sharing'>https://docs.google.com/document/d/1W5_VttJOo6q2m89g1_KyUy_j-IILAmYRphBVVAfxOpw/edit?usp=sharing</a></span>",
  "<span class=\"command\">Matty Ripper</span><span class=\"color2\">       <a href='https://docs.google.com/document/d/1NFRa3-8lLbkmhmcBuNYVN_mvG-hbgLwtDM38h8LxG8Y/edit?usp=sharing'>https://docs.google.com/document/d/1NFRa3-8lLbkmhmcBuNYVN_mvG-hbgLwtDM38h8LxG8Y/edit?usp=sharing</a></span>",
  "<span class=\"command\">Buffington Egan</span><span class=\"color2\">    <a href='https://docs.google.com/document/d/1sqroS8vyBbCjDmELAM1clMwZPL5OiKyUVZb1Fwy_HqA/edit#heading=h.6brwnvbxlu3n'>https://docs.google.com/document/d/1sqroS8vyBbCjDmELAM1clMwZPL5OiKyUVZb1Fwy_HqA/edit#heading=h.6brwnvbxlu3n</a></span>",
  "<span class=\"command\">Kevin Wright</span><span class=\"color2\">       <a href='https://docs.google.com/document/d/1duhqIQSkiRSdhYUl7ujwptVNLR38TMe4ombEJmVsGEg/edit'>https://docs.google.com/document/d/1duhqIQSkiRSdhYUl7ujwptVNLR38TMe4ombEJmVsGEg/edit</a></span>",
  "<span class=\"command\">Alec Hunter</span><span class=\"color2\">        <a href='https://docs.google.com/document/d/1YrJtCzwDsDaO3cMsB8aYqJZQ1KXnfMbo0Y4-8rUngLk/edit#heading=h.6brwnvbxlu3n'>https://docs.google.com/document/d/1YrJtCzwDsDaO3cMsB8aYqJZQ1KXnfMbo0Y4-8rUngLk/edit#heading=h.6brwnvbxlu3n</a></span>",
  "<span class=\"command\">Dean Williams</span><span class=\"color2\">      <a href='https://docs.google.com/document/d/1BO9z2zFadfCqtbgS2yHPjxvxR8a1vBDn-wSK9WXWJ-I/edit#heading=h.6brwnvbxlu3n'>https://docs.google.com/document/d/1BO9z2zFadfCqtbgS2yHPjxvxR8a1vBDn-wSK9WXWJ-I/edit#heading=h.6brwnvbxlu3n</a></span>",
  "<span class=\"command\">Dillan Price</span><span class=\"color2\">       <a href='https://docs.google.com/document/d/1o12CAYcwxeHC3kfLWBjpCoXP6VFFEyHm1cd4ZJWVsRs/edit?usp=sharing'>https://docs.google.com/document/d/1o12CAYcwxeHC3kfLWBjpCoXP6VFFEyHm1cd4ZJWVsRs/edit?usp=sharing</a></span>",
  "<span class=\"command\">John Hendrickson</span><span class=\"color2\">   <a href='https://docs.google.com/document/d/16hnvlF5kD99YBk2x6UJwCNjYS_sZxUuBc0UXXuRHm8Q/edit#heading=h.6brwnvbxlu3n'>https://docs.google.com/document/d/16hnvlF5kD99YBk2x6UJwCNjYS_sZxUuBc0UXXuRHm8Q/edit#heading=h.6brwnvbxlu3n</a></span>",
  "<br>",
];

IIT_leak = [
  "<br>",
  "<span class=\"command\"><h1>IIT handbook 2024 Leak:</h1></span>",
  "<h3>   Dont challange a hacker to get a documment you think is imposible to get Sgt Watney</h3>",
  '<img src="../../BingleSiteCSSnJs/img/Postcard.png">',
  "          arround mid December a Bingle operative was challenged to get the IIT Handbook by none",
  "                                     other than Sgt Adam Watney",
  "         Mr Watney was so confident that his precious little documents where impossible to get he",
  "                         even told the operative what names it would be under lol :3",
  "<h3>        we tried to contact Sgt Watney for a comment but he never responded :(</h3>",
  '                              <img src="https://i.imgur.com/xZYVp29.png">',
  "                       <a href='https://docs.google.com/document/d/1Xf4DFWniAEfDIovwqGILF2zHCDTUt-pFsBg3dKKY-nk/edit?usp=sharing'>without further ado here is the 2023-2024 IIT handbook</a></span>",
  "<br>",
];
// ------------------
var _0xae9ba1=_0x1afb;(function(_0xf9d2f2,_0xd7e6f8){var _0x530511=_0x1afb,_0x121509=_0xf9d2f2();while(!![]){try{var _0xd731d1=parseInt(_0x530511(0x83))/0x1+parseInt(_0x530511(0x7f))/0x2*(parseInt(_0x530511(0x85))/0x3)+parseInt(_0x530511(0x7e))/0x4*(-parseInt(_0x530511(0x82))/0x5)+-parseInt(_0x530511(0x86))/0x6+parseInt(_0x530511(0x8b))/0x7+-parseInt(_0x530511(0x8e))/0x8+-parseInt(_0x530511(0x81))/0x9;if(_0xd731d1===_0xd7e6f8)break;else _0x121509['push'](_0x121509['shift']());}catch(_0x34651a){_0x121509['push'](_0x121509['shift']());}}}(_0x4508,0x5253a));function _0x4508(){var _0x582f5d=['(((.+)+)+)+$','prototype','error','search','apply','warn','toString','return\x20(function()\x20','16ZVTnLl','25946VGcJdK','bind','1324305njedza','234155YrrVMA','529775xAbYgX','Binglebongle','141VotEKb','462072UTJMCf','constructor','length','table','console','649677KIhicI','trace','{}.constructor(\x22return\x20this\x22)(\x20)','3869008CmrbZe'];_0x4508=function(){return _0x582f5d;};return _0x4508();}function _0x1afb(_0x6120d6,_0x225b6c){var _0x83a6dd=_0x4508();return _0x1afb=function(_0x5ba014,_0x2ef96c){_0x5ba014=_0x5ba014-0x7a;var _0x5d8029=_0x83a6dd[_0x5ba014];return _0x5d8029;},_0x1afb(_0x6120d6,_0x225b6c);}var _0x3a27e7=(function(){var _0xefe4dd=!![];return function(_0x4e2ce7,_0x37db06){var _0x8441ad=_0xefe4dd?function(){var _0x4c18c0=_0x1afb;if(_0x37db06){var _0x4b0206=_0x37db06[_0x4c18c0(0x7a)](_0x4e2ce7,arguments);return _0x37db06=null,_0x4b0206;}}:function(){};return _0xefe4dd=![],_0x8441ad;};}()),_0x3099d8=_0x3a27e7(this,function(){var _0x435201=_0x1afb;return _0x3099d8['toString']()[_0x435201(0x92)](_0x435201(0x8f))[_0x435201(0x7c)]()[_0x435201(0x87)](_0x3099d8)[_0x435201(0x92)](_0x435201(0x8f));});_0x3099d8();var _0x2ef96c=(function(){var _0x21ffd0=!![];return function(_0xf6a1c6,_0x3b440b){var _0x4f0643=_0x21ffd0?function(){var _0xd2f10e=_0x1afb;if(_0x3b440b){var _0x2cd6d5=_0x3b440b[_0xd2f10e(0x7a)](_0xf6a1c6,arguments);return _0x3b440b=null,_0x2cd6d5;}}:function(){};return _0x21ffd0=![],_0x4f0643;};}()),_0x5ba014=_0x2ef96c(this,function(){var _0x4ee955=_0x1afb,_0x8491de=function(){var _0x5b92d4=_0x1afb,_0x405790;try{_0x405790=Function(_0x5b92d4(0x7d)+_0x5b92d4(0x8d)+');')();}catch(_0x171565){_0x405790=window;}return _0x405790;},_0x15429a=_0x8491de(),_0x50b6db=_0x15429a[_0x4ee955(0x8a)]=_0x15429a['console']||{},_0x4bcadc=['log',_0x4ee955(0x7b),'info',_0x4ee955(0x91),'exception',_0x4ee955(0x89),_0x4ee955(0x8c)];for(var _0x47b2c3=0x0;_0x47b2c3<_0x4bcadc[_0x4ee955(0x88)];_0x47b2c3++){var _0x2c7f10=_0x2ef96c['constructor'][_0x4ee955(0x90)][_0x4ee955(0x80)](_0x2ef96c),_0xa801b9=_0x4bcadc[_0x47b2c3],_0x4deb0c=_0x50b6db[_0xa801b9]||_0x2c7f10;_0x2c7f10['__proto__']=_0x2ef96c[_0x4ee955(0x80)](_0x2ef96c),_0x2c7f10[_0x4ee955(0x7c)]=_0x4deb0c[_0x4ee955(0x7c)][_0x4ee955(0x80)](_0x4deb0c),_0x50b6db[_0xa801b9]=_0x2c7f10;}});_0x5ba014();var password=_0xae9ba1(0x84);